### ISSUE TITLE
API key

### ISSUE THREAD

**Issue by netthinks** [DanielSiepmann/iw_immo#1]
Hi,
where or how can I add Immowelt API key? EM has no settings button...

**Comment by DanielSiepmann** [comment]
Since TYPO3 CMS 9.5 this has moved to the new "Settings" module within the "ADMIN TOOLS" area.

There you find the "Extension Configuration":

![image](https://user-images.githubusercontent.com/354250/48936468-55ebde00-ef0b-11e8-935e-29019a5d087f.png)
